// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Cfg is an autogenerated mock type for the cfg type
type Cfg struct {
	mock.Mock
}

// GetServerAddress provides a mock function with given fields:
func (_m *Cfg) GetServerAddress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetServerAddress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetStoreInterval provides a mock function with given fields:
func (_m *Cfg) GetStoreInterval() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStoreInterval")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// NewCfg creates a new instance of Cfg. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCfg(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cfg {
	mock := &Cfg{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
