// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cfg is an autogenerated mock type for the cfg type
type Cfg struct {
	mock.Mock
}

// GetDatabaseConnectionString provides a mock function with given fields:
func (_m *Cfg) GetDatabaseConnectionString() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseConnectionString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetFileStoragePath provides a mock function with given fields:
func (_m *Cfg) GetFileStoragePath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFileStoragePath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetRestore provides a mock function with given fields:
func (_m *Cfg) GetRestore() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRestore")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewCfg creates a new instance of Cfg. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCfg(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cfg {
	mock := &Cfg{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
