// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cfg is an autogenerated mock type for the cfg type
type Cfg struct {
	mock.Mock
}

// NewCfg creates a new instance of Cfg. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCfg(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cfg {
	mock := &Cfg{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
